name: Print environment variable

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "nightly"


env:
  ANDROID_SIGNING_KEY: '${{ secrets.ANDROID_SIGNING_KEY }}'
  
  
run: echo FUCK
#run: echo ${{ env.ANDROID_SIGNING_KEY }}
