name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday
  ANDROID_SIGNING_KEY: '${{ secrets.ANDROID_SIGNING_KEY }}'

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona

  greeting_job2:
    runs-on: ubuntu-latest
    steps:
      - name: "ANDROID_SIGNING_KEY"
        run: echo "${{ secrets.ANDROID_SIGNING_KEY }}"

  greeting_job3:
    runs-on: ubuntu-latest
    steps:
      - name: "ANDROID_KEY_PASSWORD"
        run: echo "$ANDROID_KEY_PASSWORD"
        
  greeting_job4:
    runs-on: ubuntu-latest
    steps:
      - name: "ANDROID_SIGNING_KEY"
      # if: env.ANDROID_SIGNING_KEY != null
      run: echo "${{ secrets.ANDROID_SIGNING_KEY }}"