name: Print Android Signing Key

on:
  push:
    branches:
      - main
env:
  ANDROID_SIGNING_KEY: '${{ secrets.ANDROID_SIGNING_KEY }}'


jobs:
  print-signing-key:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Android Signing Key
      run: echo "ANDROID_SIGNING_KEY"
